# Generated by Django 3.2 on 2022-08-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company/%y/%m/%d')),
                ('subtitle', models.CharField(max_length=500)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('address', models.TextField(max_length=500)),
                ('phone_numper', models.TextField(max_length=500)),
                ('email', models.TextField(max_length=500)),
                ('call_us', models.CharField(max_length=500)),
                ('email_us', models.EmailField(max_length=254)),
            ],
        ),
    ]
