# Generated by Django 3.2 on 2022-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categury',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('feature', 'feature'), ('sale', 'sale'), ('new', 'new'), ('old', 'old')], max_length=10, verbose_name='Flag'),
        ),
    ]
