# Generated by Django 3.2 on 2022-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220828_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='prodect-image/%y/%m/%d', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('old', 'old'), ('new', 'new'), ('feature', 'feature'), ('sale', 'sale')], max_length=10, verbose_name='Flag'),
        ),
    ]
